# docker-compose
version: '3.7'

services:
  app:
    build: frontend
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./frontend/:/home/node/app
      - node_modules_app:/home/node/app/node_modules

  api:
    build: backend
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./backend/:/home/node/app
      - node_modules_api:/home/node/app/node_modules

volumes:
  node_modules_app:
  node_modules_api:
